{% set name = "des-pizza-cutter" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/beckermr/pizza-cutter/archive/{{ version }}.tar.gz
  sha256: 1f2168e59ac2c48f3a84811529cca2092f409042645e8088a8000c6d44702179

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python
    - numpy
    - scipy
    - galsim
    - fitsio
    - pyyaml
    - numba
    - des-easyaccess
    - des-desmeds
    - meds
    - ngmix
    - click
    - esutil
    - sep
    - joblib
    - jinja2
    - tqdm
    - piff
    - cfitsio
    - metadetect
    - importlib_metadata

test:
  imports:
    - pizza_cutter
  commands:
    - python -c "import pizza_cutter; assert pizza_cutter.__version__ == '{{ version }}'"

about:
  home: https://github.com/beckermr/pizza-cutter
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: yummy survey slices!

extra:
  recipe-maintainers:
    - beckermr
