{% set name = "des-pizza-cutter" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/beckermr/pizza-cutter/archive/{{ version }}.tar.gz
  sha256: fa9c564f91ee3f21d1c67578cf7ae2cb6b2b19d042577fec0d9c0c3683147074

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python
    - numpy
    - scipy
    - galsim
    - fitsio
    - pyyaml
    - numba
    - des-easyaccess
    - des-desmeds
    - meds
    - ngmix
    - click
    - esutil
    - piff
    - cfitsio
    - importlib_metadata
    - hilbertcurve
    - pixmappy

test:
  imports:
    - pizza_cutter
  commands:
    - python -c "import pizza_cutter; assert pizza_cutter.__version__ == '{{ version }}'"

about:
  home: https://github.com/beckermr/pizza-cutter
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: yummy survey slices!

extra:
  recipe-maintainers:
    - beckermr
