{% set name = "des-pizza-cutter" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/beckermr/pizza-cutter/archive/{{ version }}.tar.gz
  sha256: bf793f70eed92e49ba46b15e3baf91fa3cbefc420e9592a5d33b4a36f810a06d

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools_scm <6.1
    - setuptools_scm_git_archive
  run:
    - python
    - numpy
    - scipy
    - galsim
    - fitsio
    - pyyaml
    - numba
    - des-easyaccess
    - des-desmeds
    - des-y6utils
    - meds
    - ngmix
    - click
    - esutil
    - piff
    - cfitsio
    - importlib_metadata
    - hilbertcurve
    - pixmappy

test:
  imports:
    - pizza_cutter
  commands:
    - python -c "import pizza_cutter; assert pizza_cutter.__version__ == '{{ version }}'"

about:
  home: https://github.com/beckermr/pizza-cutter
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: yummy survey slices!

extra:
  recipe-maintainers:
    - beckermr
