{% set name = "des-pizza-cutter" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/beckermr/pizza-cutter/archive/{{ version }}.tar.gz
  sha256: 6df12d56093d8df5ee863f088d5e2809613a6d6cd044bb21454811759597dccf

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - galsim
    - fitsio
    - pyyaml
    - numba
    - des-easyaccess
    - des-desmeds
    - meds
    - ngmix
    - click
    - esutil
    - sep
    - joblib
    - jinja2
    - tqdm
    - piff
    - cfitsio
    - metadetect

test:
  imports:
    - pizza_cutter

about:
  home: https://github.com/beckermr/pizza-cutter
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: yummy survey slices!

extra:
  recipe-maintainers:
    - beckermr
